feat: add new sector iterator function
armink/FlashDB pull request #206
Opened 2023-03-16 03:56 UTC by shihang-zhang

feat: add new sector iterator function to start iterating from last gc sector.)

2023-04-07 04:09 UTC, armink commented on src/fdb_kvdb.c
> +    db->oldest_addr = 0;
第一次上电时要遍历整个数据区扇区，从而找到最旧的扇区，不能写死的

2023-04-08 21:17 UTC, shihang-zhang commented on src/fdb_kvdb.c
> +    db->oldest_addr = 0;
请问应该怎样找到最旧的扇区？没有找到和这个信息相关的代码

2023-04-09 04:02 UTC, armink commented on src/fdb_kvdb.c
> +    db->oldest_addr = 0;
这块有和 @weiguang-fan 沟通过，要不你们先同步一下吧

2023-04-12 03:27 UTC, shihang-zhang commented on src/fdb_kvdb.c
> +    db->oldest_addr = 0;
Hi armink, 我根据和weiguang讨论后的理解，提交了代码。请你帮忙review代码看看是否我对设计的实现有偏差。代码目前还未经过测试，只做讨论使用。Thanks！

2023-04-19 01:52 UTC, shihang-zhang commented
Hi armink,
I have done a test and please refer to the following for some of the test log. The code runs as designed. 
Thanks!

[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 3, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 2, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00000000
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00000800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00000800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00001000
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00001000
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00001800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00001800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00000000
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00000000
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00000800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00000800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00001000
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00001000
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00001800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00001800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00000000
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00000000
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00000800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1425) Trigger a GC check after created KV.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1295) The remain empty sector is 1, GC threshold is 1.
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1265) Collect a sector @0x00000800
[FlashDB][kv][knx_os] (E:\3\0302lmg\Component\flashdb\src\FlashDB\src\fdb_kvdb.c:1277) oldest_addr is @0x00001000

2023-04-20 02:35 UTC, armink requested changes

2023-04-20 02:35 UTC, armink commented on src/fdb_kvdb.c
> +        }
L1074-L1081 的逻辑可以放到 get_next_sector_addr 里吗？

get_next_sector_addr 中检测到，下一个扇区如果超过最旧的扇区，则返回 FAILED_ADDR

这样 L821-L824 代码可能也就无需再做调整了

2023-04-20 02:35 UTC, armink commented on src/fdb_kvdb.c
> +    }
这里的 else 没用了可以删除

2023-04-20 02:35 UTC, armink commented on src/fdb_kvdb.c
> +
整体的代码风格希望和 FlashDB 原有的风格保持一致，否则会有很多无关改动。多种代码风格揉在一起，整体看起来也不太协调

2023-04-21 01:42 UTC, shihang-zhang commented on src/fdb_kvdb.c
> +    }
Done

2023-04-21 01:45 UTC, shihang-zhang commented on src/fdb_kvdb.c
> +
我对代码风格手动修改了一下，尽量和原风格保持一致。帮忙看看还有遗漏的地方吗？起因之前在我自己的vs code工程中修改过代码，导致部分代码被自动format了。多谢！

2023-04-21 01:53 UTC, shihang-zhang commented on src/fdb_kvdb.c
> +        }
get_next_sector_addr在整个文件里面被多次调用，如果改动它的逻辑，也需要将调用它时候的起始sec_addr = 0;也做修改。尤其在fdb_kv_iterate函数里面iterate起始sector地址不是0，逻辑上没有想明白如果修改get_next_sector_addr后是否有其他影响？

2023-04-21 05:41 UTC, armink commented on src/fdb_kvdb.c
> +        }
好的，这块后面我来改改吧

2023-04-21 06:47 UTC, merged

2023-04-21 06:48 UTC, armink commented
感谢 @shihang-zhang ，PR 已经合并了