Fix memory overridden
armink/FlashDB pull request #209
Opened 2023-04-03 03:08 UTC by shihang-zhang

Some of the memory access operations are out of boundary.

2023-04-03 05:13 UTC, armink commented
这个改动会不会导致 PR https://github.com/armink/FlashDB/pull/191 想要的功能无效？

2023-04-03 05:14 UTC, armink requested changes

2023-04-03 05:14 UTC, armink commented on src/fdb_kvdb.c
> +        memset(&sec_hdr, 0xFF, sizeof(struct sector_hdr_data));
```suggestion
        memset(&sec_hdr, FDB_BYTE_ERASED, sizeof(struct sector_hdr_data));
```

2023-04-03 05:14 UTC, armink commented on src/fdb_kvdb.c
> +    memset(&kv_hdr, 0xFF, sizeof(struct kv_hdr_data));
```suggestion
    memset(&kv_hdr, FDB_BYTE_ERASED, sizeof(struct kv_hdr_data));
```

2023-04-03 05:14 UTC, armink commented on inc/fdb_def.h
> -
还原无关改动

2023-04-04 01:53 UTC, shihang-zhang commented
> 这个改动会不会导致 PR #191 想要的功能无效？

这些修改是针对读取数据的动作，应不会对之前的对齐操作产生影响。

2023-04-04 08:45 UTC, armink commented on inc/fdb_def.h
> -
这个行尾和 kvdb.c 的行尾空行都还原一下哈

2023-04-06 15:18 UTC, merged